### ISSUE TITLE
Unknown error occurred message

### ISSUE THREAD

**Issue by redgular** [chadsmith/OpenVBX-Plugin-Live-Calls#1]
This used to work just fine but now there is an unknown error message that comes up. 
Console reads : Failed to load resource : .../p/calls?json&_=1487962281351

I checked the permissions and they are set to read and write. 

Any help would be greatly appreciated.

**Comment by minaevd** [comment]
Have you checked your web server logs? What is the version of php you're using?

--
Regards,
Dmitry

Enhanced and improved cloud based OpenVBX: https://www.verbery.com/
Twilio App Store: http://store.verbery.com/

**Comment by redgular** [comment]
PHP 5.6

**Comment by redgular** [comment]
I still can seem to figure out why this isn't working. Anyone else having the same problem?

**Comment by minaevd** [comment]
Have you checked your web server logs? To allow extensive logging please modify OpenVBX/config/config.php file, set $config['log_threshold'] = 4;
Can you look at the Chrome console, Network tab and see what's the return value for this /p/calls?json&_=1487962281351 ? You can also open this url in browser and see what is shown.

--
Dmitry

**Comment by redgular** [comment]
It looks like while the call is in-process I get an error 500 from that url. but once the call is completed I get a 200

**Comment by minaevd** [comment]
redgular, let me ask for the 3rd time: is there anything in your web server logs?

**Comment by redgular** [comment]
yea. the log server shows there is a 500 status on those urls. 
GET /p/calls?json&_=1489422697220 HTTP/1.0" 500
Thats what it reads in the Chrome network tab as well. 
By the way I really appreciate the help. Thank you.

![image](https://cloud.githubusercontent.com/assets/6036854/23873319/090d0348-0808-11e7-945e-ce315d91a659.png)

**Comment by redgular** [comment]
Hi. I see that the bottom was cut off. 
This is the rest of the log error. 

PHP Fatal error:  Uncaught exception 'Services_Twilio_RestException' with message 'PageToken is required for paging.' in /var/www/html/OpenVBX/libraries/Services/Twilio.php:305\nStack trace:\n#0 /var/www/html/OpenVBX/libraries/Services/Twilio.php(174): Services_Twilio->_processResponse(Array)\n#1 /var/www/html/OpenVBX/libraries/Services/Twilio.php(194): Services_Twilio->_makeIdempotentRequest(Array, '/2010-04-01/Acc...', 1)\n#2 /var/www/html/OpenVBX/libraries/Services/Twilio/ListResource.php(125): Services_Twilio->retrieveData('/2010-04-01/Acc...', Array)\n#3 /var/www/html/OpenVBX/libraries/Services/Twilio/ListResource.php(200): Services_Twilio_ListResource->getPage(1, 50, Array, NULL)\n#4 [internal function]: Services_Twilio_ListResource->getPageGenerator(1, 50, Array, NULL)\n#5 /var/www/html/OpenVBX/libraries/Services/Twilio/AutoPagingIterator.php(103): call_user_func_array(Array, Array)\n#6 /var/www/html/OpenVBX/libraries/Services/Twilio/AutoPagingIterator.php(76): Services_Twilio_AutoPagingIterator->loadIfNecessary()\n#7 /var/www/h in /var/www/html/OpenVBX/libraries/Services/Twilio.php on line 305, referer:

**Comment by endtone** [comment]
Hi, 
Thanks for your effort for making this plugin. 

I have the same issue. 
I just installed this problem and whenever an active call is on, I get an error 500 error message int the browser console aswell as an Open VBX error modal appears.


/p/calls?json&_=14879681351 (some similar number). 

Any clues? 

Thanks

**Comment by redgular** [comment]
@endtone I still haven't been able to fix it either. If I come across a way to get it working I'll let you know.
